;asserisce inizialmente tutte le patologie, i relativi sintomi e le categorie alle quali appartengono

;;;;;;;;;;;;;;;;;;;;;;;;
;;; PATOLOGIE FUNGHI ;;;
;;;;;;;;;;;;;;;;;;;;;;;;
(deffacts initial_patologie
    (desease(name peronospora)
            (category funghi))
    (symptom(desease peronospora)
            (structure foglia)
            (name macchiaforma)
            (value regolare))
    (symptom(desease peronospora)
            (structure foglia)
            (name macchiacolore) 
            (value giallo))
    (symptom(desease peronospora)
            (structure foglia)
            (name muffa)
            (value bianca))      
    (symptom(desease peronospora)
            (structure foglia)
            (name disseccamento) 
            (value si))
    
    (symptom(desease peronospora)
            (structure infiorescenza)
            (name colore)
            (value bruno))
    (symptom(desease peronospora)
            (structure infiorescenza)
            (name deformazione)
            (value si))

    (symptom(desease peronospora)
            (structure grappolo)
            (name deformazione)
            (value si))
    (symptom(desease peronospora)
            (structure grappolo)
            (name disseccamento)
            (value si))
    (symptom(desease peronospora)
            (structure grappolo)
            (name muffa)
            (value grigia))
    (symptom(desease peronospora)
            (structure grappolo)
            (name macchiacolore)
            (value verde))


    ;(desease(name oidio)
    ;          (category funghi)) 
    ;(symptom(desease oidio)
    ;        (structure foglia)
    ;        (macchiacolore giallo)
    ;        (deformazione si))
    ;(symptom(desease oidio)
    ;        (structure foglia)
    ;        (macchiacolore scuro)
    ;        (deformazione si))
    ;(symptom(desease oidio)
    ;        (structure infiorescenza)
    ;        (colore bianco)
    ;        (deformazione si))
    ;(symptom(desease oidio)
    ;        (structure grappolo)
    ;        (caduta si)
    ;        (muffa bianca))
    ;(symptom(desease oidio)
    ;        (structure tralcio)
    ;        (muffa bianca) 
    ;        (deformazione si))                    
    
    (desease(name marciumeradicale)
            (category funghi))  
    (symptom(desease marciumeradicale)
            (structure foglia)
            (name disseccamento)
            (value si))

    (symptom(desease marciumeradicale)
            (structure ceppo)
            (name macchiacolore)
            (value bianco))
    
    (symptom(desease marciumeradicale)
            (structure radice)
            (name macchiacolore)
            (value bianco))                                                                   
    ;
    ;(desease(name marciumenero)
    ;        (category funghi))
    ;(symptom(desease marciumenero)
    ;        (structure foglia)
    ;        (colore bruno)
    ;        (macchiaforma regolare))
    ;(symptom(desease marciumenero)
    ;        (structure infiorescenza)
    ;        (tacche si)
    ;        (colore scuro)
    ;        (fattoredsm aborto))
    ;(symptom(desease marciumenero)
    ;        (structure grappolo)
    ;        (macchiacolore bianco))
    ;(symptom(desease marciumenero)
    ;        (structure grappolo)
    ;        (macchiacolore bruno))
    ;(symptom(desease marciumenero)
    ;        (structure grappolo)
    ;        (macchiacolore nero))

    (desease(name marciumebianco)
            (category funghi))
    ;OR
    (symptom(desease marciumebianco)
            (structure grappolo)        
            (name macchiacolore)
            (value giallo))
    (symptom(desease marciumebianco)
            (structure grappolo)
            (name macchiacolore)
            (value bianco))
    (symptom(desease marciumebianco)
            (structure grappolo)
            (name macchiacolore)
            (value bruno))
    ;end OR
    (symptom(desease marciumebianco)
            (structure grappolo)
            (name muffa)
            (value scura))

    (symptom(desease marciumebianco)
            (structure tralcio)
            (name tacche)
            (value si))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; FITOPLASMI DELLA VITE ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(desease(name fitoplasmidellavite)
    ;          (category fitoplasmi))
    ;(symptom(desease fitoplasmidellavite)
    ;        (structure ceppo))
    ;(symptom(desease fitoplasmidellavite)
    ;        (structure foglia)
    ;        (colore giallo)
    ;        (deformazione si)
    ;        (caduta si))
    ;(symptom(desease fitoplasmidellavite)
    ;        (structure foglia)
    ;        (colore rosso)
    ;        (deformazione si)
    ;        (caduta si))
    ;(symptom(desease fitoplasmidellavite)
    ;        (structure grappolo)
    ;        (disseccamento si)
    ;        (caduta si))
    ;(symptom(desease fitoplasmidellavite)
    ;        (structure tralcio)
    ;        (fattoredsm basso)
    ;        (macchiacolore nero)
    ;        (macchiaforma puntiforme))

;;;;;;;;;;;;;;;
;;; INSETTI ;;;
;;;;;;;;;;;;;;;
    (desease(name cocciniglia)
            (category insetti))
    (symptom(desease cocciniglia)
            (structure foglia)
            (name disseccamento)
            (value si))
    (symptom(desease cocciniglia)
            (structure foglia)
            (name melatafumag)
            (value si))

    (symptom(desease cocciniglia)
            (structure grappolo)
            (name fattoredsm)
            (value basso))
;
    ;(desease(name tetranichidae)
    ;        (category insetti))
    ;(symptom(desease tetranichidae)
    ;        (structure foglia)
    ;        (colore giallo)
    ;        (macchiaforma puntiforme)
    ;        (disseccamento si))
    ;(symptom(desease tetranichidae)
    ;        (structure foglia)
    ;        (colore rosso)
    ;        (macchiaforma puntiforme)
    ;        (disseccamento si))
    ;(symptom(desease tetranichidae)
    ;        (structure grappolo)
    ;        (fattoredsm basso))

;;;;;;;;;;;;;
;;; VIRUS ;;;
;;;;;;;;;;;;;
   ; (desease(name legnoriccio)
   ;         (category virus))
   ; (symptom(desease legnoriccio)
   ;         (structure foglia)
   ;         (colore giallo))
   ; (symptom(desease legnoriccio)
   ;         (structure tralcio)
   ;         (fattoredsm basso))
   ; (symptom(desease legnoriccio)
   ;         (structure ceppo)
   ;         (tacche si))
;
   ; (desease(name accartocciamento)
   ;         (category virus))
   ; (symptom(desease accartocciamento)
   ;         (structure foglia)
   ;         (deformazione si)
   ;         (colore rosso))
   ; (symptom(desease accartocciamento)
   ;         (structure grappolo)
   ;         (fattoredsm basso))
   ; (symptom(desease accartocciamento)
   ;         (structure tralcio)
   ;         (fattoredsm irregolare))
)
