;asserisce inizialmente tutte le patologie, i relativi sintomi e le categorie alle quali appartengono

;;;;;;;;;;;;;;;;;;;;;;;;
;;; PATOLOGIE FUNGHI ;;;
;;;;;;;;;;;;;;;;;;;;;;;;
(deffacts initial_patologie
    (patologia(nome peronospora)
              (categoria funghi))
    (sintomo(nome peronospora)
            (struttura foglia)
            (macchiaforma regolare)
            (macchiacolore giallo)
            (muffa bianca)      
            (disseccamento si))
    (sintomo(nome peronospora)
            (struttura infiorescenza)
            (colore bruno)
            (deformazione si))
    (sintomo(nome peronospora)
            (struttura grappolo)
            (deformazione si)
            (disseccamento si)) 

    ;(patologia(nome oidio)
    ;          (categoria funghi)) 
    ;(sintomo(nome oidio)
    ;        (struttura foglia)
    ;        (macchiacolore giallo)
    ;        (deformazione si))
    ;(sintomo(nome oidio)
    ;        (struttura foglia)
    ;        (macchiacolore scuro)
    ;        (deformazione si))
    ;(sintomo(nome oidio)
    ;        (struttura infiorescenza)
    ;        (colore bianco)
    ;        (deformazione si))
    ;(sintomo(nome oidio)
    ;        (struttura grappolo)
    ;        (caduta si)
    ;        (muffa bianca))
    ;(sintomo(nome oidio)
    ;        (struttura tralcio)
    ;        (muffa bianca) 
    ;        (deformazione si))                    
    
    (patologia(nome marciumeradicale)
            (categoria funghi))  
    (sintomo(nome marciumeradicale)
            (struttura foglia)
            (disseccamento si))
    (sintomo(nome marciumeradicale)
            (struttura ceppo)
            (macchiacolore bianco))
    (sintomo(nome marciumeradicale)
            (struttura radice)
            (macchiacolore bianco))                                                                   
    ;
    ;(patologia(nome marciumenero)
    ;        (categoria funghi))
    ;(sintomo(nome marciumenero)
    ;        (struttura foglia)
    ;        (colore bruno)
    ;        (macchiaforma regolare))
    ;(sintomo(nome marciumenero)
    ;        (struttura infiorescenza)
    ;        (tacche si)
    ;        (colore scuro)
    ;        (fattoredsm aborto))
    ;(sintomo(nome marciumenero)
    ;        (struttura grappolo)
    ;        (macchiacolore bianco))
    ;(sintomo(nome marciumenero)
    ;        (struttura grappolo)
    ;        (macchiacolore bruno))
    ;(sintomo(nome marciumenero)
    ;        (struttura grappolo)
    ;        (macchiacolore nero))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; FITOPLASMI DELLA VITE ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(patologia(nome fitoplasmidellavite)
    ;          (categoria fitoplasmi))
    ;(sintomo(nome fitoplasmidellavite)
    ;        (struttura ceppo))
    ;(sintomo(nome fitoplasmidellavite)
    ;        (struttura foglia)
    ;        (colore giallo)
    ;        (deformazione si)
    ;        (caduta si))
    ;(sintomo(nome fitoplasmidellavite)
    ;        (struttura foglia)
    ;        (colore rosso)
    ;        (deformazione si)
    ;        (caduta si))
    ;(sintomo(nome fitoplasmidellavite)
    ;        (struttura grappolo)
    ;        (disseccamento si)
    ;        (caduta si))
    ;(sintomo(nome fitoplasmidellavite)
    ;        (struttura tralcio)
    ;        (fattoredsm basso)
    ;        (macchiacolore nero)
    ;        (macchiaforma puntiforme))

;;;;;;;;;;;;;;;
;;; INSETTI ;;;
;;;;;;;;;;;;;;;
    (patologia(nome cocciniglia)
            (categoria insetti))
    (sintomo(nome cocciniglia)
            (struttura foglia)
            (disseccamento si)
            (melatafumag si))
    (sintomo(nome cocciniglia)
            (struttura grappolo)
            (fattoredsm basso))
;
    ;(patologia(nome tetranichidae)
    ;        (categoria insetti))
    ;(sintomo(nome tetranichidae)
    ;        (struttura foglia)
    ;        (colore giallo)
    ;        (macchiaforma puntiforme)
    ;        (disseccamento si))
    ;(sintomo(nome tetranichidae)
    ;        (struttura foglia)
    ;        (colore rosso)
    ;        (macchiaforma puntiforme)
    ;        (disseccamento si))
    ;(sintomo(nome tetranichidae)
    ;        (struttura grappolo)
    ;        (fattoredsm basso))

;;;;;;;;;;;;;
;;; VIRUS ;;;
;;;;;;;;;;;;;
   ; (patologia(nome legnoriccio)
   ;         (categoria virus))
   ; (sintomo(nome legnoriccio)
   ;         (struttura foglia)
   ;         (colore giallo))
   ; (sintomo(nome legnoriccio)
   ;         (struttura tralcio)
   ;         (fattoredsm basso))
   ; (sintomo(nome legnoriccio)
   ;         (struttura ceppo)
   ;         (tacche si))
;
   ; (patologia(nome accartocciamento)
   ;         (categoria virus))
   ; (sintomo(nome accartocciamento)
   ;         (struttura foglia)
   ;         (deformazione si)
   ;         (colore rosso))
   ; (sintomo(nome accartocciamento)
   ;         (struttura grappolo)
   ;         (fattoredsm basso))
   ; (sintomo(nome accartocciamento)
   ;         (struttura tralcio)
   ;         (fattoredsm irregolare))
)

;(defrule faidomanda
;    (fai domanda)
;    =>
;    ;sostituire insetti con categoria più probabile
;    ;sostituire 2 con 1 per prendere il counter più alto
;    (bind ?fact (get_rank_pos insetti 1))
;    (bind ?sintomo (nth$ 1 (fact-slot-value ?fact (nth$ 4 (fact-slot-names ?fact)))))
;    (bind ?struttura (fact-slot-value ?fact (nth$ 2 (fact-slot-names ?fact))))
;    (bind ?resp (generate_question ?struttura ?sintomo))
;    (if (eq ?resp no)
;        then     (retract *)
;                (batch "test#assert.clp")
;    (retract ?fact) ;esempio fatto melatafumag
;    (init_rank_assertions)
;        else (assert (sintomo-utente ?sintomo ?resp))
;    )
;
;)


;(nth$ 1 (fact-slot-values 347 (fact-slot-names 347))) 